<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Payments Export</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #333;
        }
        .header p {
            margin: 5px 0 0 0;
            color: #666;
        }
        .filters {
            margin-bottom: 20px;
            padding: 10px;
            background-color: #f5f5f5;
            border-radius: 5px;
        }
        .filters h3 {
            margin: 0 0 10px 0;
            font-size: 14px;
            color: #333;
        }
        .filters p {
            margin: 2px 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
            color: #333;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .status-confirmed {
            color: #28a745;
            font-weight: bold;
        }
        .status-pending {
            color: #ffc107;
            font-weight: bold;
        }
        .status-failed {
            color: #dc3545;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Payments Export Report</h1>
        <p>Generated on: {{ $exported_at }}</p>
    </div>

    @if($search || $status !== 'all')
    <div class="filters">
        <h3>Applied Filters:</h3>
        @if($search)
            <p><strong>Search:</strong> "{{ $search }}"</p>
        @endif
        @if($status !== 'all')
            <p><strong>Status:</strong> {{ ucfirst($status) }}</p>
        @endif
    </div>
    @endif

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Attendee Name</th>
                <th>Phone</th>
                <th>Event</th>
                <th>Amount</th>
                <th>M-Pesa Code</th>
                <th>Status</th>
                <th>Method</th>
                <th>Created At</th>
                <th>Actioned By</th>
                <th>Actioned At</th>
            </tr>
        </thead>
        <tbody>
            @forelse($payments as $payment)
                <tr>
                    <td>{{ $payment->id }}</td>
                    <td>{{ $payment->attendee?->name ?? '-' }}</td>
                    <td>{{ $payment->attendee?->whatsapp ?? '-' }}</td>
                    <td>{{ $payment->attendee?->event?->name ?? '-' }}</td>
                    <td>Ksh. {{ number_format($payment->amount, 2) }}</td>
                    <td>{{ $payment->mpesa_code }}</td>
                    <td class="status-{{ $payment->status }}">
                        {{ ucfirst($payment->status) }}
                    </td>
                    <td>{{ ucfirst($payment->method) }}</td>
                    <td>{{ $payment->created_at?->format('Y-m-d H:i:s') ?? '-' }}</td>
                    <td>{{ $payment->actionedBy?->name ?? '-' }}</td>
                    <td>{{ $payment->actioned_at?->format('Y-m-d H:i:s') ?? '-' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="11" style="text-align: center; padding: 20px;">
                        No payments found matching the criteria.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>Total Records: {{ $payments->count() }}</p>
        <p>Report generated by OLQP Singles Dinner Management System</p>
    </div>
</body>
</html>
